blank_issues_enabled: false
contact_links:
  - name: Carlos Urias
    url: mailto:carlos@carlosurias.com
    about: Si tienes algÃºn problema, por favor envia un correo con toda la informaciÃ³n

# Plantillas de Issues
issue_templates:
  - name: "ğŸš€ New Feature Request"
    description: "Plantilla para solicitudes de nuevas funcionalidades."
    filename: "feature-request.yml"
  - name: "ğŸ Bug Report"
    description: "Plantilla para reportar errores o bugs en el sistema."
    filename: "bug-report.yml"
  - name: "ğŸ“‹ Documentation"
    description: "Plantilla para solicitudes o mejoras en la documentaciÃ³n."
    filename: "documentation-request.yml"
